export enum ExceptionLocalCode {
  // common
  GENERIC_ERROR = 10000,
  INVARIANT_VIOLATION,
  NOT_IMPLEMENTED_ERROR,
  NOT_ALLOWED_VALUE,
  DISABLE_FUNCTIONALITY,
  NOT_FOUND,
  TRY_AGAIN_LATER,
  MAX_15_DIGITS,
  NON_EXISTENT_GUARD,
  MODULE_LOAD_FAILED,
  UNKNOWN_FILTER_FIELD,

  // user
  USER_STORE_FAILED = 10500,
  USER_SAVE_FAILED,
  USER_NAME_EXISTS,
  EMAIL_EXISTS,
  USER_NOT_FOUND,
  USER_IS_BANNED,
  ADMIN_USER_NOT_EXIST,
  WRONG_OLD_PASSWORD,
  WRONG_PASSWORD,
  NEW_PASSWORD_CONFIRMATION_FAILED,
  NO_PERMISSION,

  // auth
  AUTH_USER_VALIDATION_FAILED = 10600,
  AUTH_WRONG_TOKEN,
  AUTH_TOKEN_EXPIRED,
  AUTH_EMAIL_CONFIRMATION_FAILED,
  AUTH_PHONE_CONFIRMATION_FAILED,
  AUTH_REGISTRATION_FAILED,
  AUTH_PASSWORD_RECOVERY_FAILED,
  ADMIN_AUTH_USER_VALIDATION_FAILED,
  AUTH_CODE_CHECK_FAIL,
  AUTH_EMAIL_CODE_NOT_SENT,

  // notifications
  TELEGRAM_NOT_LINKED = 10900,
  NOTIFICATION_SEND_FAILED,
  NOTIFICATION_NOT_EXIST,
  NOTIFICATION_ALREADY_READ,

  // referral program
  REFERRAL_PROGRAM_DISABLED = 11000,

  // file
  FILE_STORE_FAILED = 11300,

  // codes
  CODE_NOT_EXISTS = 12500,

  // Auth2 factor
  AUTH_2FA_ENABLE = 12600,
  AUTH_2FA_DISABLE,
  AUTH_2FA_GET_SECRET,
  AUTH_2FA_MISSING_2FA_CODE_FIELD,
  AUTH_2FA_INVALID_2FA_CODE,
}
