export enum LanguageCode {
  EN = 'EN',
  ES = 'ES',
  FR = 'FR',
  ID = 'ID',
  ZH = 'ZH',
  JA = 'JA',
  DE = 'DE',
  RU = 'RU',
  PT = 'PT',
  EL = 'EL',
  IT = 'IT',
  KO = 'KO',
  MS = 'MS',
  TH = 'TH',
  VI = 'VI',
  HI = 'HI',
  NL = 'NL',
}

export const localeName: { [key in LanguageCode]: string } = {
  [LanguageCode.EN]: 'English',
  [LanguageCode.ES]: 'Spanish',
  [LanguageCode.FR]: 'French',
  [LanguageCode.ID]: 'Indonesian',
  [LanguageCode.ZH]: 'Chinese',
  [LanguageCode.JA]: 'Japanese',
  [LanguageCode.DE]: 'German',
  [LanguageCode.RU]: 'Russian',
  [LanguageCode.PT]: 'Portuguese',
  [LanguageCode.EL]: 'Greek',
  [LanguageCode.IT]: 'Italian',
  [LanguageCode.KO]: 'Korean',
  [LanguageCode.MS]: 'Malay',
  [LanguageCode.TH]: 'Thai',
  [LanguageCode.VI]: 'Vietnamese',
  [LanguageCode.HI]: 'Hindi',
  [LanguageCode.NL]: 'Dutch',
};
